#! /bin/sh


### CONFIGURATIONS
bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          7
bspc config split_ratio          0.50

bspc config focused_border_color  "#81A1C1"
bspc config normal_border_color   "#2E3440"
bspc config active_border_color   "#B48EAD"
bspc config presel_feedback_color "#A3BE8C"

bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle false
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

### RULES
bspc rule -r *:*

declare -a files=(Lxterminal Pcmanfm qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

declare -a files=(firefox TelegramDesktop)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

declare -a files=(libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice nvim)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

declare -a code=(mpv Inkscape)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

### AUTOSTART
killall -9 sxhkd polybar unclutter

polybar --config=~/.config/polybar/config.ini &

unclutter &

sxhkd
